spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    profiles:
      active: local

application:
  jwt:
    secretKey: ync.ac.kr.secret-key-1234567890!@#$
    expiration: 900000 # 15분
    refreshExpiration: 86400000 # 1일
